# Form implementation generated from reading ui file 'ui/nouranui.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import pyqtgraph as pg

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(977, 798)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("\n"
"QMainWindow {\n"
"    background-color:#000000;\n"
"}\n"
"QDialog {\n"
"    background-color:#000000;\n"
"}\n"
"QColorDialog {\n"
"    background-color:#000000;\n"
"}\n"
"QTextEdit {\n"
"    background-color:#000000;\n"
"    color: #a9b7c6;\n"
"}\n"
"QPlainTextEdit {\n"
"    selection-background-color:#f39c12;\n"
"    background-color:#000000;\n"
"    border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-bottom-color: transparent;\n"
"    border-width: 1px;\n"
"    color: #a9b7c6;\n"
"}\n"
"QPushButton{\n"
"    border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-bottom-color: transparent;\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    color: #a9b7c6;\n"
"    padding: 2px;\n"
"    background-color: #000000;\n"
"}\n"
"QPushButton::default{\n"
"    border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-bottom-color: #e67e22;\n"
"    border-width: 1px;\n"
"    color: #a9b7c6;\n"
"    padding: 2px;\n"
"    background-color: #000000;\n"
"}\n"
"QPushButton:hover{\n"
"    border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-bottom-color: #e67e22;\n"
"    border-bottom-width: 1px;\n"
"    border-radius: 6px;\n"
"    border-style: solid;\n"
"    color: #FFFFFF;\n"
"    padding-bottom: 2px;\n"
"    background-color: #000000;\n"
"}\n"
"QPushButton:pressed{\n"
"    border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-bottom-color: #e67e22;\n"
"    border-bottom-width: 2px;\n"
"    border-radius: 6px;\n"
"    border-style: solid;\n"
"    color: #e67e22;\n"
"    padding-bottom: 1px;\n"
"    background-color: #000000;\n"
"}\n"
"QPushButton:disabled{\n"
"    border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-bottom-color: transparent;\n"
"    border-bottom-width: 2px;\n"
"    border-radius: 6px;\n"
"    border-style: solid;\n"
"    color: #808086;\n"
"    padding-bottom: 1px;\n"
"    background-color: #000000;\n"
"}\n"
"QToolButton {\n"
"    border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-bottom-color: #e67e22;\n"
"    border-bottom-width: 1px;\n"
"    border-style: solid;\n"
"    color: #a9b7c6;\n"
"    padding: 2px;\n"
"    background-color: #000000;\n"
"}\n"
"QToolButton:hover{\n"
"    border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-bottom-color: #e67e22;\n"
"    border-bottom-width: 2px;\n"
"    border-radius: 6px;\n"
"    border-style: solid;\n"
"    color: #FFFFFF;\n"
"    padding-bottom: 1px;\n"
"    background-color: #000000;\n"
"}\n"
"QLineEdit {\n"
"    border-width: 1px; border-radius: 4px;\n"
"    border-color: rgb(58, 58, 58);\n"
"    border-style: inset;\n"
"    padding: 0 8px;\n"
"    color: #a9b7c6;\n"
"    background:#000000;\n"
"    selection-background-color:#007b50;\n"
"    selection-color: #FFFFFF;\n"
"}\n"
"QLabel {\n"
"    color: #a9b7c6;\n"
"}\n"
"QLCDNumber {\n"
"    color: #e67e22;\n"
"}\n"
"QProgressBar {\n"
"    text-align: center;\n"
"    color: rgb(240, 240, 240);\n"
"    border-width: 1px; \n"
"    border-radius: 10px;\n"
"    border-color: rgb(58, 58, 58);\n"
"    border-style: inset;\n"
"    background-color:#000000;\n"
"}\n"
"QProgressBar::chunk {\n"
"    background-color: #e67e22;\n"
"    border-radius: 5px;\n"
"}\n"
"QMenu{\n"
"    background-color:#000000;\n"
"}\n"
"QMenuBar {\n"
"    background:rgb(0, 0, 0);\n"
"    color: #a9b7c6;\n"
"}\n"
"QMenuBar::item {\n"
"      spacing: 3px; \n"
"    padding: 1px 4px;\n"
"      background: transparent;\n"
"}\n"
"QMenuBar::item:selected { \n"
"      border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-bottom-color: #e67e22;\n"
"    border-bottom-width: 1px;\n"
"    border-radius: 6px;\n"
"    border-style: solid;\n"
"    color: #FFFFFF;\n"
"    padding-bottom: 0px;\n"
"    background-color: #000000;\n"
"}\n"
"QMenu::item:selected {\n"
"    border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: #e67e22;\n"
"    border-bottom-color: transparent;\n"
"    border-left-width: 2px;\n"
"    color: #FFFFFF;\n"
"    padding-left:15px;\n"
"    padding-top:4px;\n"
"    padding-bottom:4px;\n"
"    padding-right:7px;\n"
"    background-color:#000000;\n"
"}\n"
"QMenu::item {\n"
"    border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-bottom-color: transparent;\n"
"    border-bottom-width: 1px;\n"
"    border-style: solid;\n"
"    color: #a9b7c6;\n"
"    padding-left:17px;\n"
"    padding-top:4px;\n"
"    padding-bottom:4px;\n"
"    padding-right:7px;\n"
"    background-color:#000000;\n"
"}\n"
"QTabWidget {\n"
"    color:rgb(0,0,0);\n"
"    background-color:#000000;\n"
"}\n"
"QTabWidget::pane {\n"
"        border-color: rgb(77,77,77);\n"
"        background-color:#000000;\n"
"        border-style: solid;\n"
"        border-width: 1px;\n"
"        border-radius: 6px;\n"
"}\n"
"QTabBar::tab {\n"
"    border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-bottom-color: transparent;\n"
"    border-bottom-width: 1px;\n"
"    border-style: solid;\n"
"    color: #808086;\n"
"    padding: 3px;\n"
"    margin-left:3px;\n"
"    background-color:#000000;\n"
"}\n"
"QTabBar::tab:selected, QTabBar::tab:last:selected, QTabBar::tab:hover {\n"
"      border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-bottom-color: #e67e22;\n"
"    border-bottom-width: 2px;\n"
"    border-style: solid;\n"
"    color: #FFFFFF;\n"
"    padding-left: 3px;\n"
"    padding-bottom: 2px;\n"
"    margin-left:3px;\n"
"    background-color:#000000;\n"
"}\n"
"\n"
"QCheckBox {\n"
"    color: #a9b7c6;\n"
"    padding: 2px;\n"
"}\n"
"QCheckBox:disabled {\n"
"    color: #808086;\n"
"    padding: 2px;\n"
"}\n"
"\n"
"QCheckBox:hover {\n"
"    border-radius:4px;\n"
"    border-style:solid;\n"
"    padding-left: 1px;\n"
"    padding-right: 1px;\n"
"    padding-bottom: 1px;\n"
"    padding-top: 1px;\n"
"    border-width:1px;\n"
"    border-color: rgb(87, 97, 106);\n"
"    background-color:#000000;\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    border-style:solid;\n"
"    border-width: 1px;\n"
"    border-color: #e67e22;\n"
"    color: #a9b7c6;\n"
"    background-color: #e67e22;\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    border-style:solid;\n"
"    border-width: 1px;\n"
"    border-color: #e67e22;\n"
"    color: #a9b7c6;\n"
"    background-color: transparent;\n"
"}\n"
"QRadioButton {\n"
"    color: #a9b7c6;\n"
"    background-color:#000000;\n"
"    padding: 1px;\n"
"}\n"
"QRadioButton::indicator:checked {\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    border-style:solid;\n"
"    border-radius:5px;\n"
"    border-width: 1px;\n"
"    border-color: #e67e22;\n"
"    color: #a9b7c6;\n"
"    background-color: #e67e22;\n"
"}\n"
"QRadioButton::indicator:!checked {\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    border-style:solid;\n"
"    border-radius:5px;\n"
"    border-width: 1px;\n"
"    border-color: #e67e22;\n"
"    color: #a9b7c6;\n"
"    background-color: transparent;\n"
"}\n"
"QStatusBar {\n"
"    color:#027f7f;\n"
"}\n"
"QSpinBox {\n"
"    color: #a9b7c6;    \n"
"    background-color:#000000;\n"
"}\n"
"QDoubleSpinBox {\n"
"    color: #a9b7c6;    \n"
"    background-color:#000000;\n"
"}\n"
"QTimeEdit {\n"
"    color: #a9b7c6;    \n"
"    background-color:#000000;\n"
"}\n"
"QDateTimeEdit {\n"
"    color: #a9b7c6;    \n"
"    background-color:#000000;\n"
"}\n"
"QDateEdit {\n"
"    color: #a9b7c6;    \n"
"    background-color:#000000;\n"
"}\n"
"QComboBox {\n"
"    color: #a9b7c6;    \n"
"    background: #1e1d23;\n"
"}\n"
"QComboBox:editable {\n"
"    background: #1e1d23;\n"
"    color: #a9b7c6;\n"
"    selection-background-color:#000000;\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    color: #a9b7c6;    \n"
"    background: #1e1d23;\n"
"    selection-color: #FFFFFF;\n"
"    selection-background-color:#000000;\n"
"}\n"
"QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n"
"    color: #a9b7c6;    \n"
"    background: #1e1d23;\n"
"}\n"
"QFontComboBox {\n"
"    color: #a9b7c6;    \n"
"    background-color:#000000;\n"
"}\n"
"QToolBox {\n"
"    color: #a9b7c6;\n"
"    background-color:#000000;\n"
"}\n"
"QToolBox::tab {\n"
"    color: #a9b7c6;\n"
"    background-color:#000000;\n"
"}\n"
"QToolBox::tab:selected {\n"
"    color: #FFFFFF;\n"
"    background-color:#000000;\n"
"}\n"
"QScrollArea {\n"
"    color: #FFFFFF;\n"
"    background-color:#000000;\n"
"}\n"
"QSlider::groove:horizontal {\n"
"    height: 5px;\n"
"    background: #e67e22;\n"
"}\n"
"QSlider::groove:vertical {\n"
"    width: 5px;\n"
"    background: #e67e22;\n"
"}\n"
"QSlider::handle:horizontal {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #b4b4b4, stop:1 #8f8f8f);\n"
"    border: 1px solid #5c5c5c;\n"
"    width: 14px;\n"
"    margin: -5px 0;\n"
"    border-radius: 7px;\n"
"}\n"
"QSlider::handle:vertical {\n"
"    background: qlineargradient(x1:1, y1:1, x2:0, y2:0, stop:0 #b4b4b4, stop:1 #8f8f8f);\n"
"    border: 1px solid #5c5c5c;\n"
"    height: 14px;\n"
"    margin: 0 -5px;\n"
"    border-radius: 7px;\n"
"}\n"
"QSlider::add-page:horizontal {\n"
"    background: white;\n"
"}\n"
"QSlider::add-page:vertical {\n"
"    background: white;\n"
"}\n"
"QSlider::sub-page:horizontal {\n"
"    background: #e67e22;\n"
"}\n"
"QSlider::sub-page:vertical {\n"
"    background: #e67e22;\n"
"}\n"
"QScrollBar:horizontal {\n"
"    max-height: 20px;\n"
"    background: rgb(0,0,0);\n"
"    border: 1px transparent grey;\n"
"    margin: 0px 20px 0px 20px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgba(255, 0, 0, 0), stop:0.7 rgba(255, 0, 0, 0), stop:0.71 rgb(230, 126, 34), stop:1 rgb(230, 126, 34));\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(0,0,0);\n"
"    min-width: 25px;\n"
"}\n"
"QScrollBar::handle:horizontal:hover {\n"
"    background: rgb(230, 126, 34);\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(0,0,0);\n"
"    min-width: 25px;\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"      border: 1px solid;\n"
"      border-color: rgb(0,0,0);\n"
"      background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgba(255, 0, 0, 0), stop:0.7 rgba(255, 0, 0, 0), stop:0.71 rgb(230, 126, 34), stop:1 rgb(230, 126, 34));\n"
"      width: 20px;\n"
"      subcontrol-position: right;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:horizontal:hover {\n"
"      border: 1px solid;\n"
"      border-color: rgb(0,0,0);\n"
"    border-radius: 8px;\n"
"      background: rgb(230, 126, 34);\n"
"      height: 16px;\n"
"      width: 16px;\n"
"      subcontrol-position: right;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:horizontal:pressed {\n"
"      border: 1px solid;\n"
"      border-color: grey;\n"
"    border-radius: 8px;\n"
"      background: rgb(230, 126, 34);\n"
"      height: 16px;\n"
"      width: 16px;\n"
"      subcontrol-position: right;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"      border: 1px solid;\n"
"      border-color: rgb(0,0,0);\n"
"      background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgba(255, 0, 0, 0), stop:0.7 rgba(255, 0, 0, 0), stop:0.71 rgb(230, 126, 34), stop:1 rgb(230, 126, 34));\n"
"      width: 20px;\n"
"      subcontrol-position: left;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal:hover {\n"
"      border: 1px solid;\n"
"      border-color: rgb(0,0,0);\n"
"    border-radius: 8px;\n"
"      background: rgb(230, 126, 34);\n"
"      height: 16px;\n"
"      width: 16px;\n"
"      subcontrol-position: left;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal:pressed {\n"
"      border: 1px solid;\n"
"      border-color: grey;\n"
"    border-radius: 8px;\n"
"      background: rgb(230, 126, 34);\n"
"      height: 16px;\n"
"      width: 16px;\n"
"      subcontrol-position: left;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::left-arrow:horizontal {\n"
"      border: 1px transparent grey;\n"
"      border-radius: 3px;\n"
"      width: 6px;\n"
"      height: 6px;\n"
"     background: rgb(0,0,0);\n"
"}\n"
"QScrollBar::right-arrow:horizontal {\n"
"    border: 1px transparent grey;\n"
"    border-radius: 3px;\n"
"      width: 6px;\n"
"      height: 6px;\n"
"     background: rgb(0,0,0);\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"     background: none;\n"
"} \n"
"QScrollBar:vertical {\n"
"    max-width: 20px;\n"
"    background: rgb(0,0,0);\n"
"    border: 1px transparent grey;\n"
"    margin: 20px 0px 20px 0px;\n"
"}\n"
"QScrollBar::add-line:vertical {\n"
"    border: 1px solid;\n"
"      border-color: rgb(0,0,0);\n"
"      background-color: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 0, 0, 0), stop:0.7 rgba(255, 0, 0, 0), stop:0.71 rgb(230, 126, 34), stop:1 rgb(230, 126, 34));\n"
"      height: 20px;\n"
"      subcontrol-position: bottom;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {\n"
"      border: 1px solid;\n"
"      border-color: rgb(0,0,0);\n"
"    border-radius: 8px;\n"
"      background: rgb(230, 126, 34);\n"
"      height: 16px;\n"
"      width: 16px;\n"
"      subcontrol-position: bottom;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {\n"
"      border: 1px solid;\n"
"      border-color: grey;\n"
"    border-radius: 8px;\n"
"      background: rgb(230, 126, 34);\n"
"      height: 16px;\n"
"      width: 16px;\n"
"      subcontrol-position: bottom;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical {\n"
"      border: 1px solid;\n"
"      border-color: rgb(0,0,0);\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 0, 0, 0), stop:0.7 rgba(255, 0, 0, 0), stop:0.71 rgb(230, 126, 34), stop:1 rgb(230, 126, 34));\n"
"      height: 20px;\n"
"      subcontrol-position: top;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {\n"
"      border: 1px solid;\n"
"      border-color: rgb(0,0,0);\n"
"    border-radius: 8px;\n"
"      background: rgb(230, 126, 34);\n"
"      height: 16px;\n"
"      width: 16px;\n"
"      subcontrol-position: top;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {\n"
"      border: 1px solid;\n"
"      border-color: grey;\n"
"    border-radius: 8px;\n"
"      background: rgb(230, 126, 34);\n"
"      height: 16px;\n"
"      width: 16px;\n"
"      subcontrol-position: top;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"    QScrollBar::handle:vertical {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 0, 0, 0), stop:0.7 rgba(255, 0, 0, 0), stop:0.71 rgb(230, 126, 34), stop:1 rgb(230, 126, 34));\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(0,0,0);\n"
"    min-height: 25px;\n"
"}\n"
"QScrollBar::handle:vertical:hover {\n"
"    background: rgb(230, 126, 34);\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(0,0,0);\n"
"    min-heigth: 25px;\n"
"}\n"
"QScrollBar::up-arrow:vertical {\n"
"    border: 1px transparent grey;\n"
"    border-radius: 3px;\n"
"      width: 6px;\n"
"      height: 6px;\n"
"     background: rgb(0,0,0);\n"
"}\n"
"QScrollBar::down-arrow:vertical {\n"
"      border: 1px transparent grey;\n"
"      border-radius: 3px;\n"
"      width: 6px;\n"
"      height: 6px;\n"
"     background: rgb(0,0,0);\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"      background: none;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Plot_2 = pg.GraphicsLayoutWidget(parent=self.centralwidget)
        self.Plot_2.setMinimumSize(QtCore.QSize(0, 100))
        self.Plot_2.setAutoFillBackground(False)
        self.Plot_2.setStyleSheet("")
        self.Plot_2.setObjectName("Plot_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.Plot_2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_2.addWidget(self.Plot_2)
        self.Plot_3 = pg.GraphicsLayoutWidget(parent=self.centralwidget)
        self.Plot_3.setMinimumSize(QtCore.QSize(0, 100))
        self.Plot_3.setAutoFillBackground(False)
        self.Plot_3.setStyleSheet("")
        self.Plot_3.setObjectName("Plot_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.Plot_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_2.addWidget(self.Plot_3)
        self.verticalLayout_11.addLayout(self.horizontalLayout_2)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.ZoomIn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.ZoomIn.setStyleSheet("")
        self.ZoomIn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui\\../Resources/icons8-plus-40.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.ZoomIn.setIcon(icon)
        self.ZoomIn.setIconSize(QtCore.QSize(16, 16))
        self.ZoomIn.setObjectName("ZoomIn")
        self.horizontalLayout.addWidget(self.ZoomIn)
        self.upBtn_1 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.upBtn_1.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("ui\\../Resources/icons8-chevron-up-40.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.upBtn_1.setIcon(icon1)
        self.upBtn_1.setObjectName("upBtn_1")
        self.horizontalLayout.addWidget(self.upBtn_1)
        self.ZoomOut = QtWidgets.QPushButton(parent=self.centralwidget)
        self.ZoomOut.setStyleSheet("")
        self.ZoomOut.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("ui\\../Resources/icons8-minus-40.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.ZoomOut.setIcon(icon2)
        self.ZoomOut.setIconSize(QtCore.QSize(16, 16))
        self.ZoomOut.setObjectName("ZoomOut")
        self.horizontalLayout.addWidget(self.ZoomOut)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem2)
        self.ResetBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.ResetBtn.setStyleSheet("")
        self.ResetBtn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("ui\\../Resources/icons8-restart-40.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.ResetBtn.setIcon(icon3)
        self.ResetBtn.setIconSize(QtCore.QSize(16, 16))
        self.ResetBtn.setObjectName("ResetBtn")
        self.horizontalLayout_9.addWidget(self.ResetBtn)
        self.leftBtn_1 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.leftBtn_1.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("ui\\../Resources/icons8-chevron-left-40.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.leftBtn_1.setIcon(icon4)
        self.leftBtn_1.setObjectName("leftBtn_1")
        self.horizontalLayout_9.addWidget(self.leftBtn_1)
        self.PausePlayBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.PausePlayBtn.setStyleSheet("")
        self.PausePlayBtn.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("ui\\../Resources/icons8-pause-40.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.PausePlayBtn.setIcon(icon5)
        self.PausePlayBtn.setIconSize(QtCore.QSize(20, 20))
        self.PausePlayBtn.setObjectName("PausePlayBtn")
        self.horizontalLayout_9.addWidget(self.PausePlayBtn)
        self.rightBtn_1 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.rightBtn_1.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("ui\\../Resources/icons8-right-40-2.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.rightBtn_1.setIcon(icon6)
        self.rightBtn_1.setObjectName("rightBtn_1")
        self.horizontalLayout_9.addWidget(self.rightBtn_1)
        self.RewindBtn1 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.RewindBtn1.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("ui\\../Resources/icons8-stop-40.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.RewindBtn1.setIcon(icon7)
        self.RewindBtn1.setIconSize(QtCore.QSize(20, 20))
        self.RewindBtn1.setObjectName("RewindBtn1")
        self.horizontalLayout_9.addWidget(self.RewindBtn1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem4 = QtWidgets.QSpacerItem(78, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.downBtn_1 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.downBtn_1.setMaximumSize(QtCore.QSize(314, 24))
        self.downBtn_1.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("ui\\../Resources/icons8-chevron-down-40.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.downBtn_1.setIcon(icon8)
        self.downBtn_1.setObjectName("downBtn_1")
        self.horizontalLayout_5.addWidget(self.downBtn_1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_10.addLayout(self.verticalLayout_2)
        self.LinkCheckBox = QtWidgets.QCheckBox(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LinkCheckBox.sizePolicy().hasHeightForWidth())
        self.LinkCheckBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(13)
        self.LinkCheckBox.setFont(font)
        self.LinkCheckBox.setObjectName("LinkCheckBox")
        self.horizontalLayout_10.addWidget(self.LinkCheckBox)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.ZoomIn_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.ZoomIn_2.setStyleSheet("")
        self.ZoomIn_2.setText("")
        self.ZoomIn_2.setIcon(icon)
        self.ZoomIn_2.setIconSize(QtCore.QSize(16, 16))
        self.ZoomIn_2.setObjectName("ZoomIn_2")
        self.horizontalLayout_3.addWidget(self.ZoomIn_2)
        self.upBtn_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.upBtn_2.setText("")
        self.upBtn_2.setIcon(icon1)
        self.upBtn_2.setObjectName("upBtn_2")
        self.horizontalLayout_3.addWidget(self.upBtn_2)
        self.ZoomOut_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.ZoomOut_2.setStyleSheet("")
        self.ZoomOut_2.setText("")
        self.ZoomOut_2.setIcon(icon2)
        self.ZoomOut_2.setIconSize(QtCore.QSize(16, 16))
        self.ZoomOut_2.setObjectName("ZoomOut_2")
        self.horizontalLayout_3.addWidget(self.ZoomOut_2)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem8)
        self.ResetBtn_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.ResetBtn_2.setStyleSheet("")
        self.ResetBtn_2.setText("")
        self.ResetBtn_2.setIcon(icon3)
        self.ResetBtn_2.setObjectName("ResetBtn_2")
        self.horizontalLayout_8.addWidget(self.ResetBtn_2)
        self.leftBtn_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.leftBtn_2.setText("")
        self.leftBtn_2.setIcon(icon4)
        self.leftBtn_2.setObjectName("leftBtn_2")
        self.horizontalLayout_8.addWidget(self.leftBtn_2)
        self.PausePlayBtn_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.PausePlayBtn_2.setStyleSheet("")
        self.PausePlayBtn_2.setText("")
        self.PausePlayBtn_2.setIcon(icon5)
        self.PausePlayBtn_2.setIconSize(QtCore.QSize(20, 20))
        self.PausePlayBtn_2.setObjectName("PausePlayBtn_2")
        self.horizontalLayout_8.addWidget(self.PausePlayBtn_2)
        self.rightBtn_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.rightBtn_2.setText("")
        self.rightBtn_2.setIcon(icon6)
        self.rightBtn_2.setObjectName("rightBtn_2")
        self.horizontalLayout_8.addWidget(self.rightBtn_2)
        self.RewindBtn2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.RewindBtn2.setText("")
        self.RewindBtn2.setIcon(icon7)
        self.RewindBtn2.setIconSize(QtCore.QSize(20, 20))
        self.RewindBtn2.setObjectName("RewindBtn2")
        self.horizontalLayout_8.addWidget(self.RewindBtn2)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem9)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem10)
        self.downBtn_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.downBtn_2.setText("")
        self.downBtn_2.setIcon(icon8)
        self.downBtn_2.setObjectName("downBtn_2")
        self.horizontalLayout_6.addWidget(self.downBtn_2)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem11)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_10.addLayout(self.verticalLayout)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem12)
        self.Speed_label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.Speed_label_2.setStyleSheet("font: 13pt \"Georgia\";")
        self.Speed_label_2.setObjectName("Speed_label_2")
        self.horizontalLayout_11.addWidget(self.Speed_label_2)
        self.SpeedSlider_2 = QtWidgets.QSlider(parent=self.centralwidget)
        self.SpeedSlider_2.setStyleSheet("")
        self.SpeedSlider_2.setMinimum(25)
        self.SpeedSlider_2.setMaximum(300)
        self.SpeedSlider_2.setSingleStep(25)
        self.SpeedSlider_2.setPageStep(25)
        self.SpeedSlider_2.setSliderPosition(200)
        self.SpeedSlider_2.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.SpeedSlider_2.setTickPosition(QtWidgets.QSlider.TickPosition.TicksBelow)
        self.SpeedSlider_2.setObjectName("SpeedSlider_2")
        self.horizontalLayout_11.addWidget(self.SpeedSlider_2)
        self.horizontalLayout_12.addLayout(self.horizontalLayout_11)
        spacerItem13 = QtWidgets.QSpacerItem(318, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem13)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.Speed_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.Speed_label.setStyleSheet("font: 13pt \"Georgia\";")
        self.Speed_label.setObjectName("Speed_label")
        self.horizontalLayout_7.addWidget(self.Speed_label)
        self.SpeedSlider = QtWidgets.QSlider(parent=self.centralwidget)
        self.SpeedSlider.setStyleSheet("")
        self.SpeedSlider.setMinimum(25)
        self.SpeedSlider.setMaximum(300)
        self.SpeedSlider.setSingleStep(25)
        self.SpeedSlider.setPageStep(25)
        self.SpeedSlider.setSliderPosition(200)
        self.SpeedSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.SpeedSlider.setTickPosition(QtWidgets.QSlider.TickPosition.TicksBelow)
        self.SpeedSlider.setObjectName("SpeedSlider")
        self.horizontalLayout_7.addWidget(self.SpeedSlider)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem14)
        self.horizontalLayout_12.addLayout(self.horizontalLayout_7)
        self.verticalLayout_3.addLayout(self.horizontalLayout_12)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_10.addLayout(self.verticalLayout_4)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem15)
        self.AddSignal1 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.AddSignal1.setStyleSheet("font: 13pt \"Georgia\";")
        self.AddSignal1.setObjectName("AddSignal1")
        self.horizontalLayout_4.addWidget(self.AddSignal1)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem16)
        self.AddSignal2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.AddSignal2.setStyleSheet("font: 13pt \"Georgia\";")
        self.AddSignal2.setObjectName("AddSignal2")
        self.horizontalLayout_4.addWidget(self.AddSignal2)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem17)
        self.verticalLayout_10.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.SelectChannelDropBox1 = QtWidgets.QComboBox(parent=self.centralwidget)
        self.SelectChannelDropBox1.setStyleSheet("font: 13pt \"Georgia\";")
        self.SelectChannelDropBox1.setObjectName("SelectChannelDropBox1")
        self.SelectChannelDropBox1.addItem("")
        self.horizontalLayout_13.addWidget(self.SelectChannelDropBox1)
        self.moveToRight = QtWidgets.QPushButton(parent=self.centralwidget)
        self.moveToRight.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("ui\\../Resources/icons8-right-arrow-40.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.moveToRight.setIcon(icon9)
        self.moveToRight.setIconSize(QtCore.QSize(20, 20))
        self.moveToRight.setObjectName("moveToRight")
        self.horizontalLayout_13.addWidget(self.moveToRight)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem18)
        self.moveToLeft = QtWidgets.QPushButton(parent=self.centralwidget)
        self.moveToLeft.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("ui\\../Resources/icons8-left-arrow-40.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.moveToLeft.setIcon(icon10)
        self.moveToLeft.setIconSize(QtCore.QSize(20, 20))
        self.moveToLeft.setObjectName("moveToLeft")
        self.horizontalLayout_13.addWidget(self.moveToLeft)
        self.SelectChannelDropBox2 = QtWidgets.QComboBox(parent=self.centralwidget)
        self.SelectChannelDropBox2.setStyleSheet("font: 13pt \"Georgia\";")
        self.SelectChannelDropBox2.setObjectName("SelectChannelDropBox2")
        self.SelectChannelDropBox2.addItem("")
        self.horizontalLayout_13.addWidget(self.SelectChannelDropBox2)
        self.verticalLayout_10.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem19)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.DeleteBtnCh1 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.DeleteBtnCh1.setStyleSheet("font: 13pt \"Georgia\";")
        self.DeleteBtnCh1.setObjectName("DeleteBtnCh1")
        self.verticalLayout_6.addWidget(self.DeleteBtnCh1)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.SelectColorButton1 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.SelectColorButton1.setStyleSheet("font: 13pt \"Georgia\";")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("ui\\../Resources/icons8-color-swatch-48.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.SelectColorButton1.setIcon(icon11)
        self.SelectColorButton1.setObjectName("SelectColorButton1")
        self.horizontalLayout_14.addWidget(self.SelectColorButton1)
        self.SaveSnapsotButton_1 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.SaveSnapsotButton_1.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("ui\\../Resources/icons8-screenshot-40.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.SaveSnapsotButton_1.setIcon(icon12)
        self.SaveSnapsotButton_1.setIconSize(QtCore.QSize(20, 20))
        self.SaveSnapsotButton_1.setObjectName("SaveSnapsotButton_1")
        self.horizontalLayout_14.addWidget(self.SaveSnapsotButton_1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_16.addLayout(self.verticalLayout_6)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem20)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(16)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_9.addWidget(self.pushButton)
        self.horizontalLayout_16.addLayout(self.verticalLayout_9)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem21)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.DeleteBtnCh2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.DeleteBtnCh2.setStyleSheet("font: 13pt \"Georgia\";")
        self.DeleteBtnCh2.setObjectName("DeleteBtnCh2")
        self.verticalLayout_8.addWidget(self.DeleteBtnCh2)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.SaveSnapsotButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.SaveSnapsotButton_2.setText("")
        self.SaveSnapsotButton_2.setIcon(icon12)
        self.SaveSnapsotButton_2.setIconSize(QtCore.QSize(20, 20))
        self.SaveSnapsotButton_2.setObjectName("SaveSnapsotButton_2")
        self.horizontalLayout_15.addWidget(self.SaveSnapsotButton_2)
        self.SelectColorButton2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.SelectColorButton2.setStyleSheet("font: 13pt \"Georgia\";")
        self.SelectColorButton2.setIcon(icon11)
        self.SelectColorButton2.setObjectName("SelectColorButton2")
        self.horizontalLayout_15.addWidget(self.SelectColorButton2)
        self.verticalLayout_8.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16.addLayout(self.verticalLayout_8)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem22)
        self.verticalLayout_10.addLayout(self.horizontalLayout_16)
        self.verticalLayout_11.addLayout(self.verticalLayout_10)
        self.horizontalLayout_17.addLayout(self.verticalLayout_11)
        self.SelectColorLabel1 = QtWidgets.QLabel(parent=self.centralwidget)
        self.SelectColorLabel1.setText("")
        self.SelectColorLabel1.setObjectName("SelectColorLabel1")
        self.horizontalLayout_17.addWidget(self.SelectColorLabel1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen_Signal = QtGui.QAction(parent=MainWindow)
        self.actionOpen_Signal.setObjectName("actionOpen_Signal")
        self.actionSave_Report = QtGui.QAction(parent=MainWindow)
        self.actionSave_Report.setObjectName("actionSave_Report")
        self.actionClose = QtGui.QAction(parent=MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionMake_report = QtGui.QAction(parent=MainWindow)
        self.actionMake_report.setObjectName("actionMake_report")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ZoomIn.setToolTip(_translate("MainWindow", "ZoomOut"))
        # self.upBtn_1.setShortcut(_translate("MainWindow", "Up"))
        self.ZoomOut.setToolTip(_translate("MainWindow", "ZoomOut"))
        self.ResetBtn.setToolTip(_translate("MainWindow", "restart"))
        # self.leftBtn_1.setShortcut(_translate("MainWindow", "Left"))
        self.rightBtn_1.setShortcut(_translate("MainWindow", "Right"))
        self.RewindBtn1.setToolTip(_translate("MainWindow", "stop"))
        # self.downBtn_1.setShortcut(_translate("MainWindow", "Down"))
        self.LinkCheckBox.setText(_translate("MainWindow", "  Link"))
        self.ZoomIn_2.setToolTip(_translate("MainWindow", "ZoomIn"))
        # self.upBtn_2.setShortcut(_translate("MainWindow", "Up"))
        self.ZoomOut_2.setToolTip(_translate("MainWindow", "ZoomOut"))
        self.ResetBtn_2.setToolTip(_translate("MainWindow", "restart"))
        # self.leftBtn_2.setShortcut(_translate("MainWindow", "Left"))
        # self.rightBtn_2.setShortcut(_translate("MainWindow", "Right"))
        self.RewindBtn2.setToolTip(_translate("MainWindow", "stop"))
        # self.downBtn_2.setShortcut(_translate("MainWindow", "Down"))
        self.Speed_label_2.setText(_translate("MainWindow", "Speed"))
        self.Speed_label.setText(_translate("MainWindow", "Speed"))
        self.AddSignal1.setText(_translate("MainWindow", "Browse"))
        # self.AddSignal1.setShortcut(_translate("MainWindow", "Ctrl+B"))
        self.AddSignal2.setText(_translate("MainWindow", "Browse"))
        # self.AddSignal2.setShortcut(_translate("MainWindow", "Ctrl+B"))
        self.SelectChannelDropBox1.setItemText(0, _translate("MainWindow", "Select signal"))
        self.moveToRight.setToolTip(_translate("MainWindow", "move selected signal to the right graph"))
        self.moveToLeft.setToolTip(_translate("MainWindow", "move selected signal to the left graph"))
        self.SelectChannelDropBox2.setItemText(0, _translate("MainWindow", "Select signal"))
        self.DeleteBtnCh1.setToolTip(_translate("MainWindow", "Delete selected signal"))
        self.DeleteBtnCh1.setText(_translate("MainWindow", "Delete"))
        # self.DeleteBtnCh1.setShortcut(_translate("MainWindow", "Ctrl+D"))
        self.SelectColorButton1.setToolTip(_translate("MainWindow", "Change the color of the selected signal"))
        self.SelectColorButton1.setText(_translate("MainWindow", "Color"))
        # self.SelectColorButton1.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.SaveSnapsotButton_1.setToolTip(_translate("MainWindow", "Take a Screenshot of the graph"))
        # self.SaveSnapsotButton_1.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.pushButton.setText(_translate("MainWindow", "Save pdf"))
        self.DeleteBtnCh2.setToolTip(_translate("MainWindow", "Delete selected signal"))
        self.DeleteBtnCh2.setText(_translate("MainWindow", "Delete"))
        # self.DeleteBtnCh2.setShortcut(_translate("MainWindow", "Ctrl+D"))
        self.SaveSnapsotButton_2.setToolTip(_translate("MainWindow", "Take a Screenshot of the graph"))
        # self.SaveSnapsotButton_2.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.SelectColorButton2.setToolTip(_translate("MainWindow", "Change the color of the selected signal"))
        self.SelectColorButton2.setText(_translate("MainWindow", "Color"))
        # self.SelectColorButton2.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.actionOpen_Signal.setText(_translate("MainWindow", "Open Signal"))
        self.actionSave_Report.setText(_translate("MainWindow", "Save Report"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.actionMake_report.setText(_translate("MainWindow", "Make report"))
from pyqtgraph import PlotWidget
